version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
      - ./ecosystem.config.js:/app/ecosystem.config.js
    networks:
      - shortlink-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shortlink-network
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shortlink-network
    restart: unless-stopped

networks:
  shortlink-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 